# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tomek/Dropbox/solver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tomek/Dropbox/solver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tomek/Dropbox/solver/CMakeFiles /home/tomek/Dropbox/solver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tomek/Dropbox/solver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named solver

# Build rule for target.
solver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 solver
.PHONY : solver

# fast build rule for target.
solver/fast:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/build
.PHONY : solver/fast

src/solver.o: src/solver.cpp.o
.PHONY : src/solver.o

# target to build an object file
src/solver.cpp.o:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/solver.cpp.o
.PHONY : src/solver.cpp.o

src/solver.i: src/solver.cpp.i
.PHONY : src/solver.i

# target to preprocess a source file
src/solver.cpp.i:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/solver.cpp.i
.PHONY : src/solver.cpp.i

src/solver.s: src/solver.cpp.s
.PHONY : src/solver.s

# target to generate assembly for a file
src/solver.cpp.s:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/solver.cpp.s
.PHONY : src/solver.cpp.s

src/test.o: src/test.cpp.o
.PHONY : src/test.o

# target to build an object file
src/test.cpp.o:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/test.cpp.o
.PHONY : src/test.cpp.o

src/test.i: src/test.cpp.i
.PHONY : src/test.i

# target to preprocess a source file
src/test.cpp.i:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/test.cpp.i
.PHONY : src/test.cpp.i

src/test.s: src/test.cpp.s
.PHONY : src/test.s

# target to generate assembly for a file
src/test.cpp.s:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/test.cpp.s
.PHONY : src/test.cpp.s

src/types/clause.o: src/types/clause.cpp.o
.PHONY : src/types/clause.o

# target to build an object file
src/types/clause.cpp.o:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/types/clause.cpp.o
.PHONY : src/types/clause.cpp.o

src/types/clause.i: src/types/clause.cpp.i
.PHONY : src/types/clause.i

# target to preprocess a source file
src/types/clause.cpp.i:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/types/clause.cpp.i
.PHONY : src/types/clause.cpp.i

src/types/clause.s: src/types/clause.cpp.s
.PHONY : src/types/clause.s

# target to generate assembly for a file
src/types/clause.cpp.s:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/types/clause.cpp.s
.PHONY : src/types/clause.cpp.s

src/types/literal.o: src/types/literal.cpp.o
.PHONY : src/types/literal.o

# target to build an object file
src/types/literal.cpp.o:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/types/literal.cpp.o
.PHONY : src/types/literal.cpp.o

src/types/literal.i: src/types/literal.cpp.i
.PHONY : src/types/literal.i

# target to preprocess a source file
src/types/literal.cpp.i:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/types/literal.cpp.i
.PHONY : src/types/literal.cpp.i

src/types/literal.s: src/types/literal.cpp.s
.PHONY : src/types/literal.s

# target to generate assembly for a file
src/types/literal.cpp.s:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/types/literal.cpp.s
.PHONY : src/types/literal.cpp.s

src/utils/helpers.o: src/utils/helpers.cpp.o
.PHONY : src/utils/helpers.o

# target to build an object file
src/utils/helpers.cpp.o:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/utils/helpers.cpp.o
.PHONY : src/utils/helpers.cpp.o

src/utils/helpers.i: src/utils/helpers.cpp.i
.PHONY : src/utils/helpers.i

# target to preprocess a source file
src/utils/helpers.cpp.i:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/utils/helpers.cpp.i
.PHONY : src/utils/helpers.cpp.i

src/utils/helpers.s: src/utils/helpers.cpp.s
.PHONY : src/utils/helpers.s

# target to generate assembly for a file
src/utils/helpers.cpp.s:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/utils/helpers.cpp.s
.PHONY : src/utils/helpers.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... solver"
	@echo "... src/solver.o"
	@echo "... src/solver.i"
	@echo "... src/solver.s"
	@echo "... src/test.o"
	@echo "... src/test.i"
	@echo "... src/test.s"
	@echo "... src/types/clause.o"
	@echo "... src/types/clause.i"
	@echo "... src/types/clause.s"
	@echo "... src/types/literal.o"
	@echo "... src/types/literal.i"
	@echo "... src/types/literal.s"
	@echo "... src/utils/helpers.o"
	@echo "... src/utils/helpers.i"
	@echo "... src/utils/helpers.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

